### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Ymonse** [webvenky/qr_scanning_drones#1]
Hello,

I don't found any source code in your src folder, is it normal ?

Thank you

Regards,

**Comment by bluetulip89** [comment]
Yes more input is needed on this. Document package names are mismatching with packages mentioned here. Kindly update the repo with right package

**Comment by webvenky** [comment]
Sorry. I did not notice this issue for a long time. I have re-uploaded the files in case you need them.
